### ISSUE TITLE
PWA: Offline is not working

### ISSUE THREAD

**Issue by ttbrijkishor** [nuxt/hackernews#17]
Hi during offline site is not working. demo has also has the same issue. Is PWA active.

**Comment by Alexeyporubay** [comment]
"AI is changing it all, making things easier for us. It changes the way we interact, consume information, obtain goods and services. It does what humans do, but more efficiently, quickly, and at a lower cost. How? Let’s figure out the big picture.

Artificial Intelligence, abbreviated as AI, is not one technology, but rather an umbrella term for a branch of computer science. This branch is dedicated to complex algorithms and software able to perform human-like tasks: speech and text recognition, data analysis, learning, problem-solving.

Through the analysis of complicated data and its recurrent patterns recognition, AI-powered technologies can approximate conclusions without direct human input.

AI is quite a broad field. As that field has progressed, several types of AI have emerged. The main applications of AI are machine learning, deep learning, natural language processing, image processing, and speech recognition.

Artificial intelligence can be used across all manner of industries, ripe for AI disruption. The healthcare ecosystem is no exception. AI powers healthcare by the availability of structured patient data from various databases and the rapid progress of these data analytics techniques.

Armed with AI innovative technologies, doctors can make more precise diagnoses and improve treatment plans with better predictions. Moreover, AI becomes increasingly applied in medicine development, patient monitoring, and care. As a result of AI's ability to deal with the growing database of detailed patient data, the whole healthcare industry is shifting towards preventive rather than reactionary level. Here we researched the recent advancement to answer the question: what are examples of artificial intelligence in healthcare?

More about it here: https://www.zfort.com/blog/ai-in-healthcare"
